### ISSUE TITLE
请问3-D Heatmap Predictor这部分在哪个文件里

### ISSUE THREAD

**Issue by sgrrlll** [xmuqimingxia/3D-HANet#6]

**Comment by sgrrlll** [comment]
reademe最后一段的给的链接有些错误

**Comment by xmuqimingxia** [comment]
谢谢您的提醒，‘reademe最后一段的给的链接有些错误’ 这个BUG已经修复。3-D Heatmap Predictor这个模块与CenterPoint一致，没有独特的创新，所以没有单独标注出来，热图的预测在[CenterHead.](https://github.com/xmuqimingxia/3D-HANet/blob/main/pcdet/models/dense_heads/center_head.py)

**Comment by sgrrlll** [comment]
> 谢谢您的提醒，‘reademe最后一段的给的链接有些错误’ 这个BUG已经修复。3-D Heatmap Predictor这个模块与CenterPoint一致，没有独特的创新，所以没有单独标注出来，热图的预测在[CenterHead.](https://github.com/xmuqimingxia/3D-HANet/blob/main/pcdet/models/dense_heads/center_head.py)

readme我这边点进去这两个链接指向的是同一个文件anchor_head_single.py，但是第一个链接的描述的是height_compression.py文件，height_compression.py对应的是特征传播层吗，而且该文件里的代码batch_dict['pred_hm_1'] = point_cls_1；batch_dict['pred_hm_2'] = point_cls_2这两行的pred_hm_1/2不是预测的热图吗

**Comment by xmuqimingxia** [comment]
是的，你是对的。我已经把我错误的回复删除了。非常感谢您的提醒，这个工作很久没有回顾，一些细节确实记混淆了。
