### ISSUE TITLE
请问预测热图为什么预测两个

### ISSUE THREAD

**Issue by sgrrlll** [xmuqimingxia/3D-HANet#7]
backbones_2d\map_to_bev\height_compression.py文件里在最开始把体素特征分成两部分，对这两部分分别处理得到以下两个热图---batch_dict['pred_hm_1'] = point_cls_1；batch_dict['pred_hm_2'] = point_cls_2，请问这么做的目的是什么呢，如果我想要使用预测的热图，是需要将这两部分拼接起来吗？

**Comment by xmuqimingxia** [comment]
因为BATCH_SIZE设置为2，所以分成了两个部分。他们分别对应两个batch的热图，所以这两部分是不能拼接的。后续有空的时候我会将代码优化一下。

**Comment by sgrrlll** [comment]
> 

那大的BATCH_SIZE会有什么影响吗，比如设置成4，但依旧分成两部分

**Comment by xmuqimingxia** [comment]
就当前版本的代码而言的话，BATCH_SIZE设置为4，则需要将预测热图分成四个部分：pred_hm_1、pred_hm_2、pred_hm_3、pred_hm_4
