### ISSUE TITLE
两个proposal_layer

### ISSUE THREAD

**Issue by MAI-KOKO** [xmuqimingxia/3D-HANet#9]
在anchor_head_single.py中结尾存在一个proposal_layer用于获取roi，那么为什么在casa_v_head.py还会存在proposal_layer呢

**Comment by xmuqimingxia** [comment]
casa部分的代码我是直接迁移过来的，没有注意到原作者为什么使用两个proposal_layer。我觉得删除掉一个proposal_layer应该是没有问题的。非常感谢你的问题，但是由于很久没动这块的项目了，代码应该不会重新测试、更新，抱歉！

**Comment by MAI-KOKO** [comment]
好的，谢谢你的回答
